### ISSUE TITLE
Options "wanted" and "valid" does not work when plugin orphanmedia is active

### ISSUE THREAD

**Issue by LauraEun** [lupo49/dokuwiki-plugin-orphanswanted#12]
When the Orphanmedia plugin is installed, then the Orphanswanted plugin will not show results for the options "valid" and "wanted".

Disabling the Orphanmedia plugin will show results

**Comment by jaller94** [comment]
Should be fixed in release 2023-05-30, which is now using DokuWiki's internal index.
