### ISSUE TITLE
Pages showing up as orphan even though it is linked to

### ISSUE THREAD

**Issue by jamnew** [lupo49/dokuwiki-plugin-orphanswanted#14]
I have a number of pages that show up as orphans even though they are linked to from other pages. I have verified this by clicking the page link generated by the orphanswanted plugin in the orphans table, then clicking backlinks on the page loaded, and seeing the page that links to it listed.

I have observed that when I edit the link and make it fully explicit the page stops being considered as an orphan e.g.

[[food.handling]|Food Handling Policy]] to
[[policies:risk:food.handling|Food Handling Policy]]

Then when I edit the link back it starts being listed as an orphan again e.g.

[[policies:risk:food.handling|Food Handling Policy]] to
[[food.handling]|Food Handling Policy]]

Other pages that are linked to via relative links do not appear as orphans so the problem isn't completely attributable to the fact that relative links are used.

**Comment by jjiglesias** [comment]
Hi! I was having this same issue with certain pages that showed up as orphans.

I realized that they were pages whose links contained a bibliographic mark between square brackets.

The code file helper.php has the regular expression used to match the links:
%\[\[([^\]|#]*)(#[^\]|]*)?\|?([^\]]*)]]%

Any single closing square bracket prevents a link from matching. This explains why those links in the first message with the text 'food.handling]' didn't match.

Given that helper.php only uses the data captured with the first capture group of the regular expression '([^\]|#]*)', the destination page's name, we can modify the end of the regular expression with a lookahead group, allowing single square brackets in the description part of the link, resulting:
%\[\[([^\]|#]*)(#[^\]|]*)?\|?(?=.*]])%

As far as I have tested, it works quite well.

Regards.

**Comment by jaller94** [comment]
Should be fixed in release 2023-05-30, which is now using DokuWiki's internal index.
