### ISSUE TITLE
Links with ?do= results in false flags.

### ISSUE THREAD

**Issue by shawndibble** [lupo49/dokuwiki-plugin-orphanswanted#18]
Sometimes, I make links to the edit page or the sitemap or something else. Anytime that a link has ?do=, I get a listing of do_something in orphanswanted and the backlink can't find where this link is.

IE:
If I made a link as: [[?do=index|sitemap]]
I would get a listing for link with no destination where it shows as: do_index and the backlink also fails to work.

Would be nice to omit any of these results as they are false flags.

**Comment by jaller94** [comment]
Fixed by #16.
