### ISSUE TITLE
Ignore links inside <code> tags

### ISSUE THREAD

**Issue by alandmoore** [lupo49/dokuwiki-plugin-orphanswanted#19]
I've several pages that are templates or example codes which contain nonsense links inside code tags, e.g.

```
Make hyperlinks like this:
<code>
[[some-namespace:some-page]]
</code>
```

These links show up as "wanted" pages.

Ideally, I'd want the plugin to ignore any links inside a code block like this.

**Comment by jaller94** [comment]
Can't reproduce with Detritus 2015-08-10a and orphanswanted 2012-12-05.

**Comment by jaller94** [comment]
I'm closing this issue since I still cannot reproduce it. If someone is still affected by this I would like to see it being fixed.
