### ISSUE TITLE
@include_namespace

### ISSUE THREAD

**Issue by floweh** [lupo49/dokuwiki-plugin-orphanswanted#21]
I'd love to have an @include_namespace besides the !eclude_namespace. It was made before, why not merging it? It could be faster for larger wikis and especially useful if you have one namespace under control with approval (publish plugin).

Sorry, I dont't know how to get back to the issue from the older original branch:
https://github.com/andywebber/dokuwiki-plugin-orphanswanted/pull/10

**Comment by jaller94** [comment]
duplicate of #8
