### ISSUE TITLE
Filtering for language namespace zh-cn doesn't work

### ISSUE THREAD

**Issue by tmo26** [lupo49/dokuwiki-plugin-orphanswanted#23]
I want to exclude results from zh-cn namespace, but only get back the unrendered command

"Orphaned pages exist, but nobody links to them.
~~ ORPHANSWANTED:orphans!toh:hwdata!oldwiki!cz!de!en!es!fr!hu!it!jp!pl!ru!tr!zh-cn ~~"

Everything is working fine, from 'cz' up to 'tr', but when I add 'zh-cn', it doesn't work any more.
Same for 'pt-br'

Could you fix that please?

**Comment by jaller94** [comment]
The - will be fixed by the introduction of 9169bc6.
