### ISSUE TITLE
Declaration & Compatability Errors

### ISSUE THREAD

**Issue by ERTurner** [lupo49/dokuwiki-plugin-orphanswanted#24]
I receive the following errors when installing this plugin.

The comparability error may be for PHP 7.
- Warning: Declaration of syntax_plugin_orphanswanted::handle($match, $state, $pos, &$handler) should be compatible with DokuWiki_Syntax_Plugin::handle($match, $state, $pos, Doku_Handler $handler) in C:\xampp\htdocs\dokuwiki\lib\plugins\orphanswanted\syntax.php on line 109
- Warning: Declaration of syntax_plugin_orphanswanted::render($format, &$renderer, $data) should be compatible with DokuWiki_Syntax_Plugin::render($format, Doku_Renderer $renderer, $data) in C:\xampp\htdocs\dokuwiki\lib\plugins\orphanswanted\syntax.php on line 109

**Comment by jaller94** [comment]
This should have been fixed by 9577bab in #22.
I don't have PHP 7 installed right now to confirm that.
