### ISSUE TITLE
new release?

### ISSUE THREAD

**Issue by mprins** [lupo49/dokuwiki-plugin-orphanswanted#29]
Hi @lupo49 any chance you could update the release date of the plugin in `plugin.info.txt` and on the wiki page so that the DW plugin manager knows there is an updated version available? currently it's at 2012-12-05 but there's been quite a few changes since then.

**Comment by jaller94** [comment]
You're right. I increased the version info. bb00354e7
@lupo49 granted me the push permission in March.

The main reasons I wasn't updating are an incomplete list of contributors and that I expected some people to run modified / better versions of the plugin. But for the good of most administrators I updated the version and will start working on the next update.

Thanks for the note on an overdue update.
