### ISSUE TITLE
hide pages listed in "config:hidepages"

### ISSUE THREAD

**Issue by dryoo** [lupo49/dokuwiki-plugin-orphanswanted#30]
Thanks for great plugin!!!!!

Please hide pages listed in "config:hidepages"
like "sidebar"

**Comment by jaller94** [comment]
Correct, the setting states "and other automatic indexes". Thanks for pointing this out.

**Comment by jaller94** [comment]
This problem has been fixed to my knowledge, but the issues didn't get closed.
