### ISSUE TITLE
Hyphen-bug

### ISSUE THREAD

**Issue by Dr-Yukon** [lupo49/dokuwiki-plugin-orphanswanted#37]
Plugin does not like hyphens in the name of the excluded folders

\~\~ORPHANSWANTED:wanted!ady!be!bg!cn!da!de!discuss!eo!es!fi!fr!he!hi!id!is!it!ja!ko!no!pl!playground!pt!ru!sv!tr!uk!user!en:news!en:other\~\~
work

\~\~ORPHANSWANTED:wanted!ady!be!bg!cn!da!de!discuss!eo!es!fi!fr!he!hi!id!is!it!ja!ko!no!pl!playground!pt!ru!sv!tr!uk!user!en:news!en:other!en:sci-fi\~\~
don't work

**Comment by Dr-Yukon** [comment]
Wow. I forgot to update the plugin. This problem was solved long ago. Sorry

**Comment by jaller94** [comment]
Thanks for the report though.
I really appreciate your interest in the plugin.
