### ISSUE TITLE
Plugin finds the "wanted page" if use link syntax in title

### ISSUE THREAD

**Issue by murrrf** [lupo49/dokuwiki-plugin-orphanswanted#39]
If I specify a link syntax in a header on a wiki page, that is, write `==== [[This is not link]] ====` in the source code of the page, this text does not turn into a link, but is displayed in the "Wanted pages" table. However, there are no backlinks to this name.
Since formatting in the headers does not turn into links, the plugin should also ignore such "missing pages".

**Comment by jaller94** [comment]
I haven't looked into this projects in years..., that being said:
This issue should be easy to resolve by adding the patterns of headings in the array of ignored block patterns.

https://github.com/lupo49/dokuwiki-plugin-orphanswanted/blob/625b9505f4510d35ac79e5ac3e1d6b521af46f76/helper.php#L107-L118

**Comment by murrrf** [comment]
I tried adding the following pattern to the specified location (not sure about the syntax, since I am not a php developer).
```
'@==*.*?==*@mu'
```
After that, the page with such a “link” heading disappeared from the list of  wanted pages.

**Comment by jaller94** [comment]
With the help of https://regex101.com/ I got this good-enough regex.

In the "Partially match this" section, the links in front of the heading are falsely going to be ignored. I didn't get this excluded from the match.

`@==.+==+\s*\n@u`

```
# Match this
=== heading 1 === === heading 2 ===
======== h-1 ========
======= h0 ======
====== h1 ======
===== h2 =====
==== h3 ====
=== h4 ===
== h5 ==
====== h1 ==
===== h2 ==
==== h3 ==
=== h4 ==
== h5 ==
======1==
=====2==
====3==
===4==
==5==
====== h1 ==========
===== h2 ==========
==== h3 ==========
=== h4 ==========
== h5 ==========
====== h1 ==
===== h2 ===
==== h3 ====
=== h4 =====
== h5 ======
====== h1 space afterwards == 
===== h2 space afterwards === 
==== h3 space afterwards ==== 
=== h4 space afterwards ===== 
== h5 space afterwards ====== 
====== h1 == still the heading ==
===== h2 == still the heading ==
==== h3 == still the heading ==
=== h4 == still the heading ==
== h5 == still the heading ==
=== DokuWiki == still the heading ==
=== DokuWiki === still the heading ==
=== DokuWiki ==== still the heading ==
=== DokuWiki ===== still the heading ==
=== DokuWiki ====== still the heading ==
====== ======
===== =====
==== ====
=== ===
== ==
============
===========
==========
=========
========
=======
======
=====

# Partially match this
hi ====== h1 ======
hi ===== h2 =====
hi ==== h3 ====
hi === h4 ===
hi == h5 ==
[[sidebar]] ====== h1 ======
[[sidebar]] ===== h2 =====
[[sidebar]] ==== h3 ====
[[sidebar]] === h4 ===
[[sidebar]] == h5 ==

# Don't match this
====
===
==
=
= h6 =
====== h1 ====== hi
===== h2 ===== hi
==== h3 ==== hi
=== h4 === hi
== h5 == hi
```

**Comment by murrrf** [comment]
Great, it's better than my version.

**Comment by jaller94** [comment]
Fixed in release 2023-05-30.
