### ISSUE TITLE
Pages referenced by the include plugin only are listed as orphaned

### ISSUE THREAD

**Issue by ajfre** [lupo49/dokuwiki-plugin-orphanswanted#40]
Pages referenced by the include plugin only are listed as orphaned.

**Comment by jaller94** [comment]
This plugin is unmaintained, Pull Requests are welcome.

Related statement about how this can be achieved:
https://github.com/lupo49/dokuwiki-plugin-orphanswanted/issues/9

**Comment by jaller94** [comment]
Should be fixed in release 2023-05-30, which is now using DokuWiki's internal index.
