### ISSUE TITLE
Show orphans only in a specific namespace

### ISSUE THREAD

**Issue by Salvatos** [lupo49/dokuwiki-plugin-orphanswanted#8]
I think there used to be an option to show only the orphans or wanted pages in a specific namespace? I have a page where I had the `~~ORPHANSWANTED:wanted@sub:namespace~~` syntax and it stopped working when I updated my Dokuwiki install, I think. Was it removed or did my brain make that up? Would it be possible to (re)implement?

**Comment by Grahack** [comment]
I'd be interested too !
